'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Commands
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BSR.Commands", GetType(Commands).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;RunDll32.exe van.dll,RunVAN&quot;
        '''&quot;sdclt.exe /restorewizardadmin&quot;
        '''&quot;sdclt.exe /restorewizard&quot;
        '''&quot;sdclt.exe /configure&quot;
        '''&quot;rundll32.exe shwebsvc.dll,AddNetPlaceRunDll&quot;
        '''&quot;control.exe srchadmin.dll&quot;
        '''&quot;rundll32.exe shell32.dll,Options_RunDLL 5&quot;
        '''&quot;RunDll32.exe DwmApi #104&quot;
        '''&quot;RunDll32.exe DwmApi #102&quot;
        '''&quot;rundll32.exe oobefldr.dll,ShowWelcomeCenter&quot;
        '''&quot;Rundll32.exe shell32.dll,Control_RunDLL appwiz.cpl,,0&quot;
        '''&quot;Rundll32.exe msrating.dll,RatingSetupUI&quot;
        '''&quot;Rundll32.exe shell32.dll,Control_RunDLL&quot;
        '''&quot;RunDll32.exe shell32.dll,Con [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ControlPanelCmds() As String
            Get
                Return ResourceManager.GetString("ControlPanelCmds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;ASSOC&quot;
        '''&quot;ATTRIB&quot;
        '''&quot;BREAK&quot;
        '''&quot;BCDEDIT&quot;
        '''&quot;CACLS&quot;
        '''&quot;CALL&quot;
        '''&quot;CD&quot;
        '''&quot;CHCP&quot;
        '''&quot;CHDIR&quot;
        '''&quot;CHKDSK&quot;
        '''&quot;CHKNTFS&quot;
        '''&quot;CLS&quot;
        '''&quot;CMD&quot;
        '''&quot;COLOR&quot;
        '''&quot;COMP&quot;
        '''&quot;COMPACT&quot;
        '''&quot;CONVERT&quot;
        '''&quot;COPY&quot;
        '''&quot;DATE&quot;
        '''&quot;DEL&quot;
        '''&quot;DISKCOMP&quot;
        '''&quot;DISKCOPY&quot;
        '''&quot;DISKPART&quot;
        '''&quot;DOSKEY&quot;
        '''&quot;DRIVERQUERY&quot;
        '''&quot;ECHO&quot;
        '''&quot;ENDLOCAL&quot;
        '''&quot;ERASE&quot;
        '''&quot;EXIT&quot;
        '''&quot;FC&quot;
        '''&quot;FIND&quot;
        '''&quot;FINDSTR&quot;
        '''&quot;FOR&quot;
        '''&quot;FORMAT&quot;
        '''&quot;FSUTIL&quot;
        '''&quot;FTYPE&quot;
        '''&quot;GOTO&quot;
        '''&quot;GPRESULT&quot;
        '''&quot;GRAFTABL&quot;
        '''&quot;HELP&quot;
        '''&quot;ICACLS&quot;
        '''&quot;IF&quot;
        '''&quot;LABEL&quot;
        '''&quot;MD&quot;
        '''&quot;MKDIR&quot;
        '''&quot;MKLINK&quot;
        '''&quot;MODE&quot;
        '''&quot;MORE&quot;
        '''&quot;MOVE&quot;
        '''&quot;OPENFILES&quot;
        '''&quot;PATH&quot;
        '''&quot;PAUSE&quot;
        '''&quot;POPD&quot;
        '''&quo....
        '''</summary>
        Friend Shared ReadOnly Property DOSCmds() As String
            Get
                Return ResourceManager.GetString("DOSCmds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;shell:Libraries&quot;
        '''&quot;shell:MusicLibrary&quot;
        '''&quot;shell:VideosLibrary&quot;
        '''&quot;shell:OtherUsersFolder&quot;
        '''&quot;shell:DeviceMetadataStore&quot;
        '''&quot;shell:PublicSuggestedLocations&quot;
        '''&quot;shell:SuggestedLocations&quot;
        '''&quot;shell:RecordedTVLibrary&quot;
        '''&quot;shell:UserProgramFiles&quot;
        '''&quot;shell:DocumentsLibrary&quot;
        '''&quot;shell:UserPinned&quot;
        '''&quot;shell:UsersLibrariesFolder&quot;
        '''&quot;shell:PicturesLibrary&quot;
        '''&quot;shell:ImplicitAppShortcuts&quot;
        '''&quot;shell:UserProgramFilesCommon&quot;
        '''&quot;shell:Ringtones&quot;
        '''&quot;shell:CommonRingtones&quot;
        '''&quot;shell:CommonPrograms&quot;
        '''&quot;shell:GameTasks&quot;
        '''&quot;shell:UserProfiles&quot;
        '''&quot;shell [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SpecialDirs() As String
            Get
                Return ResourceManager.GetString("SpecialDirs", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
